url: http://www.publishwhatyoufund.org
baseurl: /the-index-wowwow/

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - Rakefile
  - gen/
  - README.md
  - config.ru
  - Procfile
  - static.json
  - pages/pdf_tmpl

defaults:
  - scope:
      path: pages/pdf_tmpl
    values:
      layout: single
      extra_css:
        - static/css/pdf-styles.css

  - scope:
      path: pages/agencies
    values:
      layout: single

  - scope:
      path: pages/multiple
    values:
      layout: multiple

sass:
  style: compressed
