url: http://www.publishwhatyoufund.org
baseurl: /the-index-wowwow/

exclude:
  - requirements.txt
  - Gemfile
  - Gemfile.lock
  - vendor/
  - Rakefile
  - gen/
  - README.md
  - config.ru
  - Procfile
  - static.json
  - pdf_tmpl

defaults:
  - scope:
      path: pdf_tmpl
    values:
      layout: single
      extra_css:
        - static/css/pdf-styles.css

  - scope:
      path: pages/agencies
    values:
      layout: single
      extra_js:
        - static/js/single.js

  - scope:
      path: pages/multiple
    values:
      layout: multiple
      extra_js:
        - static/js/single.js

sass:
  style: compressed
