exclude:
  - html/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - Rakefile
  - gen/
  - 2018/TODO.md
  - README.md
  - 2018/README.md
  - config.ru
  - Procfile
  - static.json

defaults:
  - scope:
      path: 2018/agencies
    values:
      layout: 2018/single
      extra_css:
        - 2018/static/css/pdf-styles.css

  - scope:
      path: 2018/multiple
    values:
      layout: 2018/multiple
      extra_css:
        - 2018/static/css/pdf-styles.css

sass:
  style: compressed
