url: http://www.publishwhatyoufund.org
baseurl: /the-index-wowwowwow/

exclude:
  - html/
  - Gemfile
  - Gemfile.lock
  - vendor/
  - Rakefile
  - gen/
  - README.md
  - config.ru
  - Procfile
  - static.json

defaults:
  - scope:
      path: pages/agencies
    values:
      layout: single
      extra_css:
        - static/css/pdf-styles.css

  - scope:
      path: pages/multiple
    values:
      layout: multiple
      extra_css:
        - static/css/pdf-styles.css

sass:
  style: compressed
