exclude: ["Gemfile", "Gemfile.lock", "vendor/", "Rakefile", "gen/", "2018/TODO.md", "README.md", "2018/README.md"]
defaults:
  - scope:
      path: 2018/curves
    values:
      layout: 2018/curve

  - scope:
      path: 2018/agencies
    values:
      layout: 2018/agency

sass:
  style: compressed
