exclude: ["gen/", "demo/TODO.md", "README.md", "2016/README.md", "_2016/README.md", "demo/README.md"]
collections:
  "2016":
    output: true

defaults:
  - scope:
      path: 2016/donor
    values:
      layout: 2016/donor

  - scope:
      path: demo/curves
    values:
      layout: demo/curve

  - scope:
      path: demo/agencies
    values:
      layout: demo/agency
