url: http://www.publishwhatyoufund.org
baseurl: /the-index/2018

exclude:
  - requirements.txt
  - gen/
  - README.md
  - pdf_tmpl

defaults:
  - scope:
      path: pdf_tmpl
    values:
      layout: pdf_tmpl
      extra_css:
        - static/css/pdf-styles.css

  - scope:
      path: pages/agencies
    values:
      layout: single
      extra_js:
        - static/js/single.js

  - scope:
      path: pages/multiple
    values:
      layout: multiple
      extra_js:
        - static/js/single.js

sass:
  style: compressed
