exclude: ["gen/", "demo/TODO.md", "README.md", "demo/README.md"]
defaults:
  - scope:
      path: demo/curves
    values:
      layout: demo/curve

  - scope:
      path: demo/agencies
    values:
      layout: demo/agency
